### ISSUE TITLE
failed to install

### ISSUE THREAD

**Issue by ivyhzau** [deepomicslab/SuperTAD#1]
When I run make command, it showed some error message. I don't know how to solve it.
[  7%] Building CXX object CMakeFiles/SuperTAD.dir/detectorBinary.cpp.o
In file included from SuperTAD-master/data.h:18:0,
                 from detectorBinary.h:12,
                 from detectorBinary.cpp:5:
inputAndOutput.h: In instantiation of ‘static void Writer::writeTreeAsBedpe(std::string, std::vector<T*>&) [with T = binary::TreeNode; std::string = std::basic_string<char>]’:
SuperTAD-master/inputAndOutput.h:191:48:   required from ‘static void Writer::writeTree(std::string, std::vector<T*>&) [with T = binary::TreeNode; std::string = std::basic_string<char>]’
SuperTAD-master/detectorBinary.cpp:144:68:   required from here
SuperTAD-master/inputAndOutput.h:150:63: error: cannot pass objects of non-trivially-copyable type ‘std::string {aka class std::basic_string<char>}’ through ‘...’
             fprintf(stderr, "cannot open file: %s\n", filePath);
                                                               ^
SuperTAD-master/inputAndOutput.h: In instantiation of ‘static void Writer::writeTreeInShort(std::string, std::vector<T*>&) [with T = binary::TreeNode; std::string = std::basic_string<char>]’:
SuperTAD-master/inputAndOutput.h:193:48:   required from ‘static void Writer::writeTree(std::string, std::vector<T*>&) [with T = binary::TreeNode; std::string = std::basic_string<char>]’
SuperTAD-master/detectorBinary.cpp:144:68:   required from here
SuperTAD-master/inputAndOutput.h:184:63: error: cannot pass objects of non-trivially-copyable type ‘std::string {aka class std::basic_string<char>}’ through ‘...’
             fprintf(stderr, "cannot open file: %s\n", filePath);
                                                               ^
SuperTAD-master/inputAndOutput.h: In instantiation of ‘static void Writer::writeTreeIn8Cols(std::string, std::vector<T*>&) [with T = binary::TreeNode; std::string = std::basic_string<char>]’:
SuperTAD-master/inputAndOutput.h:201:48:   required from ‘static void Writer::writeTree(std::string, std::vector<T*>&) [with T = binary::TreeNode; std::string = std::basic_string<char>]’
SuperTAD-master/detectorBinary.cpp:144:68:   required from here
SuperTAD-master/inputAndOutput.h:105:63: error: cannot pass objects of non-trivially-copyable type ‘std::string {aka class std::basic_string<char>}’ through ‘...’
             fprintf(stderr, "cannot open file: %s\n", filePath);
                                                               ^
make[2]: *** [CMakeFiles/SuperTAD.dir/detectorBinary.cpp.o] Error 1
make[1]: *** [CMakeFiles/SuperTAD.dir/all] Error 2
make: *** [all] Error 2

**Comment by wangmengbo** [comment]
Please pull the latest code from master and give it a try.

**Comment by wangmengbo** [comment]
> When I run make command, it showed some error message. I don't know how to solve it.
> [ 7%] Building CXX object CMakeFiles/SuperTAD.dir/detectorBinary.cpp.o
> In file included from SuperTAD-master/data.h:18:0,
> from detectorBinary.h:12,
> from detectorBinary.cpp:5:
> inputAndOutput.h: In instantiation of ‘static void Writer::writeTreeAsBedpe(std::string, std::vector<T*>&) [with T = binary::TreeNode; std::string = std::basic_string]’:
> SuperTAD-master/inputAndOutput.h:191:48: required from ‘static void Writer::writeTree(std::string, std::vector<T*>&) [with T = binary::TreeNode; std::string = std::basic_string]’
> SuperTAD-master/detectorBinary.cpp:144:68: required from here
> SuperTAD-master/inputAndOutput.h:150:63: error: cannot pass objects of non-trivially-copyable type ‘std::string {aka class std::basic_string}’ through ‘...’
> fprintf(stderr, "cannot open file: %s\n", filePath);
> ^
> SuperTAD-master/inputAndOutput.h: In instantiation of ‘static void Writer::writeTreeInShort(std::string, std::vector<T*>&) [with T = binary::TreeNode; std::string = std::basic_string]’:
> SuperTAD-master/inputAndOutput.h:193:48: required from ‘static void Writer::writeTree(std::string, std::vector<T*>&) [with T = binary::TreeNode; std::string = std::basic_string]’
> SuperTAD-master/detectorBinary.cpp:144:68: required from here
> SuperTAD-master/inputAndOutput.h:184:63: error: cannot pass objects of non-trivially-copyable type ‘std::string {aka class std::basic_string}’ through ‘...’
> fprintf(stderr, "cannot open file: %s\n", filePath);
> ^
> SuperTAD-master/inputAndOutput.h: In instantiation of ‘static void Writer::writeTreeIn8Cols(std::string, std::vector<T*>&) [with T = binary::TreeNode; std::string = std::basic_string]’:
> SuperTAD-master/inputAndOutput.h:201:48: required from ‘static void Writer::writeTree(std::string, std::vector<T*>&) [with T = binary::TreeNode; std::string = std::basic_string]’
> SuperTAD-master/detectorBinary.cpp:144:68: required from here
> SuperTAD-master/inputAndOutput.h:105:63: error: cannot pass objects of non-trivially-copyable type ‘std::string {aka class std::basic_string}’ through ‘...’
> fprintf(stderr, "cannot open file: %s\n", filePath);
> ^
> make[2]: *** [CMakeFiles/SuperTAD.dir/detectorBinary.cpp.o] Error 1
> make[1]: *** [CMakeFiles/SuperTAD.dir/all] Error 2
> make: *** [all] Error 2

These problems are fixed. Please pull the latest code from master and give it a try.
