### ISSUE TITLE
Preparing input data

### ISSUE THREAD

**Issue by Kurotakid** [deepomicslab/SuperTAD#2]
Hi,
In your paper, you have used .hic files for the input files. 
I have some .hic files. How should I prepare input files from .hic files to use the SuperTAD tool?
Could you tell me a script to prepare input files? I want to test the SuperTAD tool using my data.
Best,
Daisuke

**Comment by ywZhangV** [comment]
Dear Daisuke,

SuperTAD adopts the matrix file (delimited by blank spaces) as input, the format can be acquired in the example data.
As for .hic file, we firstly derive contact matrices through [Juicer-dump](https://github.com/aidenlab/juicer/wiki/Data-Extraction) then transform the matrices to our input format (as easily as transforming the adjacent list to the matrix).

Should you have any questions, welcome your comment again!
Best,
Yu Wei

**Comment by charlotte-west** [comment]
Hi, 

Is there a way to parse the whole .hic file containing all chromosome interaction information to Juicer-dump and in turn SuperTAD? Maybe I am wrong, but it looks like you can only specify one chromosome at a time. 

Also, there are a few Juicer-dump options. I tried for my data the following command to specify all intra-chromosomal interactions for chr6 of my data :
`juicer dump observed NONE SRR5339787.hic 6:1:149736546 6:1:149736546 BP 10000 SRR5339787.dump`
Then the file SRR5339787.dump had the form:
`<start position> <end position> <score>`
Is this how you used Juicer-dump? Do you have a method for going from this format to your input format for SuperTAD? I took a look at the example data example_sub_GM12878_chr19_KR25kb_matrix.txt and indeed it is just a matrix of numbers with no chromosome information.

Thank you in advance for your consideration,
Charlotte

**Comment by sespesogil** [comment]
Hi Charlotte, 

Maybe you already figured it out, but newer versions of juicer allows to print dense matrices. You just need to add the parameter "-d" in the example code you shared. 

To get all chromosomes from a hic file using dump I generally loop it  through a vector of chromosomes. It should be fairly simple. 

Hope this helps.

S.
