### ISSUE TITLE
SuperTAD computing time

### ISSUE THREAD

**Issue by sespesogil** [deepomicslab/SuperTAD#3]
Hi! Thanks for the wonderful tool.

I am having issues with SuperTAD when I launch it for a full chromosome. It takes forever and it is seriously computationally expensive. It is totally ok when I use fractions of chromosomes though.  The main concern I have is that I am afraid of sectioning the chromosomes when the intention is comparing different sample conditions. I guess that would affect the results,  right?  Could you recommend any parameters to try to avoid this? Of if sectioning... how many fractions per chromosomes should I consider? 

Thanks a lot!

**Comment by ywZhangV** [comment]
Hello!

The expensive time consuming is inevitable as the algorithm aims to find the global optimal resolution, especially for the inference of multiway coding tree. We are trying to reduce the time complexity through discretization or approximation and we will publish the adapted version soon.
As for the segmentation for a full chromosome, the sectioning may interrupt the TAD. Therefore, I recommend for now it's better to use multi H=1 iteratively or binary mode to derive the hierarchies of the whole chromosome.
