### ISSUE TITLE
Application of 'multi' mode

### ISSUE THREAD

**Issue by X-xiaoyeren** [deepomicslab/SuperTAD#4]
Hello~
I have been using SuperTAD which I think is appropriate for my research, and seeing it turn from v1.0 to v1.2.
Till now, I can't using 'multi' mode to detect all length of chromosome.
Here's my code:
$ /mnt/d/SuperTAD/build/SuperTAD multi GM12878_chr21_50kb_dense.matrix -h 2 --chrom1 chr21 -r 50000
Erro like this:
{ do multi
  input file is GM12878_chr21_50kb_dense.matrix
  set H to 2 
  chrom1 lable is chr21
  set resolution to 50000 bp
  parse input
  number of bins is 963
  killed
  }

**Comment by ywZhangV** [comment]
Hi,

Thanks for your interest in our method. 
The 'multi' mode has time complexity O(n^4k^2h) and creates three tables with size n^3kh. Given your input is a 1k*1k matrix, I assume the process is automatically killed by the kernel under exceptional circumstances such as extreme resource starvation. 

We are working on the approximation algorithm for 'multi' mode with significant speedup but little loss of precision. We'll update the new version this month.

**Comment by X-xiaoyeren** [comment]
Thanks!!!





------------------ Original ------------------
From: Yuwei Zhang ***@***.***&gt;
Date: Thu,Jan 13,2022 5:47 PM
To: deepomicslab/SuperTAD ***@***.***&gt;
Cc: laofoye-xiaoyeren ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [deepomicslab/SuperTAD] Application of 'multi' mode (Issue #4)





 
Hi,
 
Thanks for your interest in our method.
 The 'multi' mode has time complexity O(n^4k^2h) and creates three tables with size n^3kh. Given your input is a 1k*1k matrix, I assume the process is automatically killed by the kernel under exceptional circumstances such as extreme resource starvation.
 
We are working on the approximation algorithm for 'multi' mode with significant speedup but little loss of precision. We'll update the new version this month.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by tolender** [comment]
Does this mean we should partition the chromosomes into smaller matrices? (I'd rather avoid this) 
Are there other settings we can change to reduce RAM usage? (Max I can use is 500GB RAM)

Will there be an update to the program where it only reads into memory a set distance from the diagonal to save on memory and runtime?

Thank you for the program!
